/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Documents } from "./Documents";
import { DocumentsCountArgs } from "./DocumentsCountArgs";
import { DocumentsFindManyArgs } from "./DocumentsFindManyArgs";
import { DocumentsFindUniqueArgs } from "./DocumentsFindUniqueArgs";
import { DeleteDocumentsArgs } from "./DeleteDocumentsArgs";
import { DocumentsService } from "../documents.service";
@graphql.Resolver(() => Documents)
export class DocumentsResolverBase {
  constructor(protected readonly service: DocumentsService) {}

  async _documentsItemsMeta(
    @graphql.Args() args: DocumentsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Documents])
  async documentsItems(
    @graphql.Args() args: DocumentsFindManyArgs
  ): Promise<Documents[]> {
    return this.service.documentsItems(args);
  }

  @graphql.Query(() => Documents, { nullable: true })
  async documents(
    @graphql.Args() args: DocumentsFindUniqueArgs
  ): Promise<Documents | null> {
    const result = await this.service.documents(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Documents)
  async deleteDocuments(
    @graphql.Args() args: DeleteDocumentsArgs
  ): Promise<Documents | null> {
    try {
      return await this.service.deleteDocuments(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
