/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TaskRequestsService } from "../taskRequests.service";
import { TaskRequestsCreateInput } from "./TaskRequestsCreateInput";
import { TaskRequests } from "./TaskRequests";
import { TaskRequestsFindManyArgs } from "./TaskRequestsFindManyArgs";
import { TaskRequestsWhereUniqueInput } from "./TaskRequestsWhereUniqueInput";
import { TaskRequestsUpdateInput } from "./TaskRequestsUpdateInput";

export class TaskRequestsControllerBase {
  constructor(protected readonly service: TaskRequestsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TaskRequests })
  @swagger.ApiBody({
    type: TaskRequestsCreateInput,
  })
  async createTaskRequests(
    @common.Body() data: TaskRequestsCreateInput
  ): Promise<TaskRequests> {
    return await this.service.createTaskRequests({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TaskRequests] })
  @ApiNestedQuery(TaskRequestsFindManyArgs)
  async taskRequestsItems(
    @common.Req() request: Request
  ): Promise<TaskRequests[]> {
    const args = plainToClass(TaskRequestsFindManyArgs, request.query);
    return this.service.taskRequestsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TaskRequests })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async taskRequests(
    @common.Param() params: TaskRequestsWhereUniqueInput
  ): Promise<TaskRequests | null> {
    const result = await this.service.taskRequests({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TaskRequests })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: TaskRequestsUpdateInput,
  })
  async updateTaskRequests(
    @common.Param() params: TaskRequestsWhereUniqueInput,
    @common.Body() data: TaskRequestsUpdateInput
  ): Promise<TaskRequests | null> {
    try {
      return await this.service.updateTaskRequests({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TaskRequests })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTaskRequests(
    @common.Param() params: TaskRequestsWhereUniqueInput
  ): Promise<TaskRequests | null> {
    try {
      return await this.service.deleteTaskRequests({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
