/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, TaskRequests as PrismaTaskRequests } from "@prisma/client";

export class TaskRequestsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TaskRequestsCountArgs, "select">
  ): Promise<number> {
    return this.prisma.taskRequests.count(args);
  }

  async taskRequestsItems(
    args: Prisma.TaskRequestsFindManyArgs
  ): Promise<PrismaTaskRequests[]> {
    return this.prisma.taskRequests.findMany(args);
  }
  async taskRequests(
    args: Prisma.TaskRequestsFindUniqueArgs
  ): Promise<PrismaTaskRequests | null> {
    return this.prisma.taskRequests.findUnique(args);
  }
  async createTaskRequests(
    args: Prisma.TaskRequestsCreateArgs
  ): Promise<PrismaTaskRequests> {
    return this.prisma.taskRequests.create(args);
  }
  async updateTaskRequests(
    args: Prisma.TaskRequestsUpdateArgs
  ): Promise<PrismaTaskRequests> {
    return this.prisma.taskRequests.update(args);
  }
  async deleteTaskRequests(
    args: Prisma.TaskRequestsDeleteArgs
  ): Promise<PrismaTaskRequests> {
    return this.prisma.taskRequests.delete(args);
  }
}
