/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TaskRequests } from "./TaskRequests";
import { TaskRequestsCountArgs } from "./TaskRequestsCountArgs";
import { TaskRequestsFindManyArgs } from "./TaskRequestsFindManyArgs";
import { TaskRequestsFindUniqueArgs } from "./TaskRequestsFindUniqueArgs";
import { DeleteTaskRequestsArgs } from "./DeleteTaskRequestsArgs";
import { TaskRequestsService } from "../taskRequests.service";
@graphql.Resolver(() => TaskRequests)
export class TaskRequestsResolverBase {
  constructor(protected readonly service: TaskRequestsService) {}

  async _taskRequestsItemsMeta(
    @graphql.Args() args: TaskRequestsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TaskRequests])
  async taskRequestsItems(
    @graphql.Args() args: TaskRequestsFindManyArgs
  ): Promise<TaskRequests[]> {
    return this.service.taskRequestsItems(args);
  }

  @graphql.Query(() => TaskRequests, { nullable: true })
  async taskRequests(
    @graphql.Args() args: TaskRequestsFindUniqueArgs
  ): Promise<TaskRequests | null> {
    const result = await this.service.taskRequests(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TaskRequests)
  async deleteTaskRequests(
    @graphql.Args() args: DeleteTaskRequestsArgs
  ): Promise<TaskRequests | null> {
    try {
      return await this.service.deleteTaskRequests(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
