/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Indicator } from "./Indicator";
import { IndicatorCountArgs } from "./IndicatorCountArgs";
import { IndicatorFindManyArgs } from "./IndicatorFindManyArgs";
import { IndicatorFindUniqueArgs } from "./IndicatorFindUniqueArgs";
import { DeleteIndicatorArgs } from "./DeleteIndicatorArgs";
import { IndicatorService } from "../indicator.service";
@graphql.Resolver(() => Indicator)
export class IndicatorResolverBase {
  constructor(protected readonly service: IndicatorService) {}

  async _indicatorsMeta(
    @graphql.Args() args: IndicatorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Indicator])
  async indicators(
    @graphql.Args() args: IndicatorFindManyArgs
  ): Promise<Indicator[]> {
    return this.service.indicators(args);
  }

  @graphql.Query(() => Indicator, { nullable: true })
  async indicator(
    @graphql.Args() args: IndicatorFindUniqueArgs
  ): Promise<Indicator | null> {
    const result = await this.service.indicator(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Indicator)
  async deleteIndicator(
    @graphql.Args() args: DeleteIndicatorArgs
  ): Promise<Indicator | null> {
    try {
      return await this.service.deleteIndicator(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
