/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { IndicatorService } from "../indicator.service";
import { IndicatorCreateInput } from "./IndicatorCreateInput";
import { Indicator } from "./Indicator";
import { IndicatorFindManyArgs } from "./IndicatorFindManyArgs";
import { IndicatorWhereUniqueInput } from "./IndicatorWhereUniqueInput";
import { IndicatorUpdateInput } from "./IndicatorUpdateInput";

export class IndicatorControllerBase {
  constructor(protected readonly service: IndicatorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Indicator })
  @swagger.ApiBody({
    type: IndicatorCreateInput,
  })
  async createIndicator(
    @common.Body() data: IndicatorCreateInput
  ): Promise<Indicator> {
    return await this.service.createIndicator({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Indicator] })
  @ApiNestedQuery(IndicatorFindManyArgs)
  async indicators(@common.Req() request: Request): Promise<Indicator[]> {
    const args = plainToClass(IndicatorFindManyArgs, request.query);
    return this.service.indicators({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Indicator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async indicator(
    @common.Param() params: IndicatorWhereUniqueInput
  ): Promise<Indicator | null> {
    const result = await this.service.indicator({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Indicator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: IndicatorUpdateInput,
  })
  async updateIndicator(
    @common.Param() params: IndicatorWhereUniqueInput,
    @common.Body() data: IndicatorUpdateInput
  ): Promise<Indicator | null> {
    try {
      return await this.service.updateIndicator({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Indicator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteIndicator(
    @common.Param() params: IndicatorWhereUniqueInput
  ): Promise<Indicator | null> {
    try {
      return await this.service.deleteIndicator({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
