/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Indicator as PrismaIndicator } from "@prisma/client";

export class IndicatorServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.IndicatorCountArgs, "select">
  ): Promise<number> {
    return this.prisma.indicator.count(args);
  }

  async indicators(
    args: Prisma.IndicatorFindManyArgs
  ): Promise<PrismaIndicator[]> {
    return this.prisma.indicator.findMany(args);
  }
  async indicator(
    args: Prisma.IndicatorFindUniqueArgs
  ): Promise<PrismaIndicator | null> {
    return this.prisma.indicator.findUnique(args);
  }
  async createIndicator(
    args: Prisma.IndicatorCreateArgs
  ): Promise<PrismaIndicator> {
    return this.prisma.indicator.create(args);
  }
  async updateIndicator(
    args: Prisma.IndicatorUpdateArgs
  ): Promise<PrismaIndicator> {
    return this.prisma.indicator.update(args);
  }
  async deleteIndicator(
    args: Prisma.IndicatorDeleteArgs
  ): Promise<PrismaIndicator> {
    return this.prisma.indicator.delete(args);
  }
}
