/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TaskSendService } from "../taskSend.service";
import { TaskSendCreateInput } from "./TaskSendCreateInput";
import { TaskSend } from "./TaskSend";
import { TaskSendFindManyArgs } from "./TaskSendFindManyArgs";
import { TaskSendWhereUniqueInput } from "./TaskSendWhereUniqueInput";
import { TaskSendUpdateInput } from "./TaskSendUpdateInput";

export class TaskSendControllerBase {
  constructor(protected readonly service: TaskSendService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TaskSend })
  @swagger.ApiBody({
    type: TaskSendCreateInput,
  })
  async createTaskSend(
    @common.Body() data: TaskSendCreateInput
  ): Promise<TaskSend> {
    return await this.service.createTaskSend({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TaskSend] })
  @ApiNestedQuery(TaskSendFindManyArgs)
  async taskSends(@common.Req() request: Request): Promise<TaskSend[]> {
    const args = plainToClass(TaskSendFindManyArgs, request.query);
    return this.service.taskSends({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TaskSend })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async taskSend(
    @common.Param() params: TaskSendWhereUniqueInput
  ): Promise<TaskSend | null> {
    const result = await this.service.taskSend({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TaskSend })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: TaskSendUpdateInput,
  })
  async updateTaskSend(
    @common.Param() params: TaskSendWhereUniqueInput,
    @common.Body() data: TaskSendUpdateInput
  ): Promise<TaskSend | null> {
    try {
      return await this.service.updateTaskSend({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TaskSend })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTaskSend(
    @common.Param() params: TaskSendWhereUniqueInput
  ): Promise<TaskSend | null> {
    try {
      return await this.service.deleteTaskSend({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
