/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TaskSend } from "./TaskSend";
import { TaskSendCountArgs } from "./TaskSendCountArgs";
import { TaskSendFindManyArgs } from "./TaskSendFindManyArgs";
import { TaskSendFindUniqueArgs } from "./TaskSendFindUniqueArgs";
import { DeleteTaskSendArgs } from "./DeleteTaskSendArgs";
import { TaskSendService } from "../taskSend.service";
@graphql.Resolver(() => TaskSend)
export class TaskSendResolverBase {
  constructor(protected readonly service: TaskSendService) {}

  async _taskSendsMeta(
    @graphql.Args() args: TaskSendCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TaskSend])
  async taskSends(
    @graphql.Args() args: TaskSendFindManyArgs
  ): Promise<TaskSend[]> {
    return this.service.taskSends(args);
  }

  @graphql.Query(() => TaskSend, { nullable: true })
  async taskSend(
    @graphql.Args() args: TaskSendFindUniqueArgs
  ): Promise<TaskSend | null> {
    const result = await this.service.taskSend(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TaskSend)
  async deleteTaskSend(
    @graphql.Args() args: DeleteTaskSendArgs
  ): Promise<TaskSend | null> {
    try {
      return await this.service.deleteTaskSend(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
