/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, TaskSend as PrismaTaskSend } from "@prisma/client";

export class TaskSendServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.TaskSendCountArgs, "select">): Promise<number> {
    return this.prisma.taskSend.count(args);
  }

  async taskSends(
    args: Prisma.TaskSendFindManyArgs
  ): Promise<PrismaTaskSend[]> {
    return this.prisma.taskSend.findMany(args);
  }
  async taskSend(
    args: Prisma.TaskSendFindUniqueArgs
  ): Promise<PrismaTaskSend | null> {
    return this.prisma.taskSend.findUnique(args);
  }
  async createTaskSend(
    args: Prisma.TaskSendCreateArgs
  ): Promise<PrismaTaskSend> {
    return this.prisma.taskSend.create(args);
  }
  async updateTaskSend(
    args: Prisma.TaskSendUpdateArgs
  ): Promise<PrismaTaskSend> {
    return this.prisma.taskSend.update(args);
  }
  async deleteTaskSend(
    args: Prisma.TaskSendDeleteArgs
  ): Promise<PrismaTaskSend> {
    return this.prisma.taskSend.delete(args);
  }
}
