/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TaskRecipients } from "./TaskRecipients";
import { TaskRecipientsCountArgs } from "./TaskRecipientsCountArgs";
import { TaskRecipientsFindManyArgs } from "./TaskRecipientsFindManyArgs";
import { TaskRecipientsFindUniqueArgs } from "./TaskRecipientsFindUniqueArgs";
import { DeleteTaskRecipientsArgs } from "./DeleteTaskRecipientsArgs";
import { TaskRecipientsService } from "../taskRecipients.service";
@graphql.Resolver(() => TaskRecipients)
export class TaskRecipientsResolverBase {
  constructor(protected readonly service: TaskRecipientsService) {}

  async _taskRecipientsItemsMeta(
    @graphql.Args() args: TaskRecipientsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TaskRecipients])
  async taskRecipientsItems(
    @graphql.Args() args: TaskRecipientsFindManyArgs
  ): Promise<TaskRecipients[]> {
    return this.service.taskRecipientsItems(args);
  }

  @graphql.Query(() => TaskRecipients, { nullable: true })
  async taskRecipients(
    @graphql.Args() args: TaskRecipientsFindUniqueArgs
  ): Promise<TaskRecipients | null> {
    const result = await this.service.taskRecipients(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TaskRecipients)
  async deleteTaskRecipients(
    @graphql.Args() args: DeleteTaskRecipientsArgs
  ): Promise<TaskRecipients | null> {
    try {
      return await this.service.deleteTaskRecipients(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
