/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TaskRecipientsService } from "../taskRecipients.service";
import { TaskRecipientsCreateInput } from "./TaskRecipientsCreateInput";
import { TaskRecipients } from "./TaskRecipients";
import { TaskRecipientsFindManyArgs } from "./TaskRecipientsFindManyArgs";
import { TaskRecipientsWhereUniqueInput } from "./TaskRecipientsWhereUniqueInput";
import { TaskRecipientsUpdateInput } from "./TaskRecipientsUpdateInput";

export class TaskRecipientsControllerBase {
  constructor(protected readonly service: TaskRecipientsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TaskRecipients })
  @swagger.ApiBody({
    type: TaskRecipientsCreateInput,
  })
  async createTaskRecipients(
    @common.Body() data: TaskRecipientsCreateInput
  ): Promise<TaskRecipients> {
    return await this.service.createTaskRecipients({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [TaskRecipients] })
  @ApiNestedQuery(TaskRecipientsFindManyArgs)
  async taskRecipientsItems(
    @common.Req() request: Request
  ): Promise<TaskRecipients[]> {
    const args = plainToClass(TaskRecipientsFindManyArgs, request.query);
    return this.service.taskRecipientsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TaskRecipients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async taskRecipients(
    @common.Param() params: TaskRecipientsWhereUniqueInput
  ): Promise<TaskRecipients | null> {
    const result = await this.service.taskRecipients({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TaskRecipients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: TaskRecipientsUpdateInput,
  })
  async updateTaskRecipients(
    @common.Param() params: TaskRecipientsWhereUniqueInput,
    @common.Body() data: TaskRecipientsUpdateInput
  ): Promise<TaskRecipients | null> {
    try {
      return await this.service.updateTaskRecipients({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TaskRecipients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTaskRecipients(
    @common.Param() params: TaskRecipientsWhereUniqueInput
  ): Promise<TaskRecipients | null> {
    try {
      return await this.service.deleteTaskRecipients({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
