/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, TaskRecipients as PrismaTaskRecipients } from "@prisma/client";

export class TaskRecipientsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TaskRecipientsCountArgs, "select">
  ): Promise<number> {
    return this.prisma.taskRecipients.count(args);
  }

  async taskRecipientsItems(
    args: Prisma.TaskRecipientsFindManyArgs
  ): Promise<PrismaTaskRecipients[]> {
    return this.prisma.taskRecipients.findMany(args);
  }
  async taskRecipients(
    args: Prisma.TaskRecipientsFindUniqueArgs
  ): Promise<PrismaTaskRecipients | null> {
    return this.prisma.taskRecipients.findUnique(args);
  }
  async createTaskRecipients(
    args: Prisma.TaskRecipientsCreateArgs
  ): Promise<PrismaTaskRecipients> {
    return this.prisma.taskRecipients.create(args);
  }
  async updateTaskRecipients(
    args: Prisma.TaskRecipientsUpdateArgs
  ): Promise<PrismaTaskRecipients> {
    return this.prisma.taskRecipients.update(args);
  }
  async deleteTaskRecipients(
    args: Prisma.TaskRecipientsDeleteArgs
  ): Promise<PrismaTaskRecipients> {
    return this.prisma.taskRecipients.delete(args);
  }
}
