/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DocumentTypesService } from "../documentTypes.service";
import { DocumentTypesCreateInput } from "./DocumentTypesCreateInput";
import { DocumentTypes } from "./DocumentTypes";
import { DocumentTypesFindManyArgs } from "./DocumentTypesFindManyArgs";
import { DocumentTypesWhereUniqueInput } from "./DocumentTypesWhereUniqueInput";
import { DocumentTypesUpdateInput } from "./DocumentTypesUpdateInput";

export class DocumentTypesControllerBase {
  constructor(protected readonly service: DocumentTypesService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DocumentTypes })
  async createDocumentTypes(
    @common.Body() data: DocumentTypesCreateInput
  ): Promise<DocumentTypes> {
    return await this.service.createDocumentTypes({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DocumentTypes] })
  @ApiNestedQuery(DocumentTypesFindManyArgs)
  async documentTypesItems(
    @common.Req() request: Request
  ): Promise<DocumentTypes[]> {
    const args = plainToClass(DocumentTypesFindManyArgs, request.query);
    return this.service.documentTypesItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DocumentTypes })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async documentTypes(
    @common.Param() params: DocumentTypesWhereUniqueInput
  ): Promise<DocumentTypes | null> {
    const result = await this.service.documentTypes({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DocumentTypes })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDocumentTypes(
    @common.Param() params: DocumentTypesWhereUniqueInput,
    @common.Body() data: DocumentTypesUpdateInput
  ): Promise<DocumentTypes | null> {
    try {
      return await this.service.updateDocumentTypes({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DocumentTypes })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDocumentTypes(
    @common.Param() params: DocumentTypesWhereUniqueInput
  ): Promise<DocumentTypes | null> {
    try {
      return await this.service.deleteDocumentTypes({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
