/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DocumentTypes } from "./DocumentTypes";
import { DocumentTypesCountArgs } from "./DocumentTypesCountArgs";
import { DocumentTypesFindManyArgs } from "./DocumentTypesFindManyArgs";
import { DocumentTypesFindUniqueArgs } from "./DocumentTypesFindUniqueArgs";
import { DeleteDocumentTypesArgs } from "./DeleteDocumentTypesArgs";
import { DocumentTypesService } from "../documentTypes.service";
@graphql.Resolver(() => DocumentTypes)
export class DocumentTypesResolverBase {
  constructor(protected readonly service: DocumentTypesService) {}

  async _documentTypesItemsMeta(
    @graphql.Args() args: DocumentTypesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DocumentTypes])
  async documentTypesItems(
    @graphql.Args() args: DocumentTypesFindManyArgs
  ): Promise<DocumentTypes[]> {
    return this.service.documentTypesItems(args);
  }

  @graphql.Query(() => DocumentTypes, { nullable: true })
  async documentTypes(
    @graphql.Args() args: DocumentTypesFindUniqueArgs
  ): Promise<DocumentTypes | null> {
    const result = await this.service.documentTypes(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DocumentTypes)
  async deleteDocumentTypes(
    @graphql.Args() args: DeleteDocumentTypesArgs
  ): Promise<DocumentTypes | null> {
    try {
      return await this.service.deleteDocumentTypes(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
