/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Regions } from "./Regions";
import { RegionsCountArgs } from "./RegionsCountArgs";
import { RegionsFindManyArgs } from "./RegionsFindManyArgs";
import { RegionsFindUniqueArgs } from "./RegionsFindUniqueArgs";
import { DeleteRegionsArgs } from "./DeleteRegionsArgs";
import { RegionsService } from "../regions.service";
@graphql.Resolver(() => Regions)
export class RegionsResolverBase {
  constructor(protected readonly service: RegionsService) {}

  async _regionsItemsMeta(
    @graphql.Args() args: RegionsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Regions])
  async regionsItems(
    @graphql.Args() args: RegionsFindManyArgs
  ): Promise<Regions[]> {
    return this.service.regionsItems(args);
  }

  @graphql.Query(() => Regions, { nullable: true })
  async regions(
    @graphql.Args() args: RegionsFindUniqueArgs
  ): Promise<Regions | null> {
    const result = await this.service.regions(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Regions)
  async deleteRegions(
    @graphql.Args() args: DeleteRegionsArgs
  ): Promise<Regions | null> {
    try {
      return await this.service.deleteRegions(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
