/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RegionsService } from "../regions.service";
import { RegionsCreateInput } from "./RegionsCreateInput";
import { Regions } from "./Regions";
import { RegionsFindManyArgs } from "./RegionsFindManyArgs";
import { RegionsWhereUniqueInput } from "./RegionsWhereUniqueInput";
import { RegionsUpdateInput } from "./RegionsUpdateInput";

export class RegionsControllerBase {
  constructor(protected readonly service: RegionsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Regions })
  async createRegions(
    @common.Body() data: RegionsCreateInput
  ): Promise<Regions> {
    return await this.service.createRegions({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Regions] })
  @ApiNestedQuery(RegionsFindManyArgs)
  async regionsItems(@common.Req() request: Request): Promise<Regions[]> {
    const args = plainToClass(RegionsFindManyArgs, request.query);
    return this.service.regionsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Regions })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async regions(
    @common.Param() params: RegionsWhereUniqueInput
  ): Promise<Regions | null> {
    const result = await this.service.regions({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Regions })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRegions(
    @common.Param() params: RegionsWhereUniqueInput,
    @common.Body() data: RegionsUpdateInput
  ): Promise<Regions | null> {
    try {
      return await this.service.updateRegions({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Regions })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRegions(
    @common.Param() params: RegionsWhereUniqueInput
  ): Promise<Regions | null> {
    try {
      return await this.service.deleteRegions({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
