/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Regions as PrismaRegions } from "@prisma/client";

export class RegionsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.RegionsCountArgs, "select">): Promise<number> {
    return this.prisma.regions.count(args);
  }

  async regionsItems(
    args: Prisma.RegionsFindManyArgs
  ): Promise<PrismaRegions[]> {
    return this.prisma.regions.findMany(args);
  }
  async regions(
    args: Prisma.RegionsFindUniqueArgs
  ): Promise<PrismaRegions | null> {
    return this.prisma.regions.findUnique(args);
  }
  async createRegions(args: Prisma.RegionsCreateArgs): Promise<PrismaRegions> {
    return this.prisma.regions.create(args);
  }
  async updateRegions(args: Prisma.RegionsUpdateArgs): Promise<PrismaRegions> {
    return this.prisma.regions.update(args);
  }
  async deleteRegions(args: Prisma.RegionsDeleteArgs): Promise<PrismaRegions> {
    return this.prisma.regions.delete(args);
  }
}
