/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Organizations } from "./Organizations";
import { OrganizationsCountArgs } from "./OrganizationsCountArgs";
import { OrganizationsFindManyArgs } from "./OrganizationsFindManyArgs";
import { OrganizationsFindUniqueArgs } from "./OrganizationsFindUniqueArgs";
import { DeleteOrganizationsArgs } from "./DeleteOrganizationsArgs";
import { OrganizationsService } from "../organizations.service";
@graphql.Resolver(() => Organizations)
export class OrganizationsResolverBase {
  constructor(protected readonly service: OrganizationsService) {}

  async _organizationsItemsMeta(
    @graphql.Args() args: OrganizationsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Organizations])
  async organizationsItems(
    @graphql.Args() args: OrganizationsFindManyArgs
  ): Promise<Organizations[]> {
    return this.service.organizationsItems(args);
  }

  @graphql.Query(() => Organizations, { nullable: true })
  async organizations(
    @graphql.Args() args: OrganizationsFindUniqueArgs
  ): Promise<Organizations | null> {
    const result = await this.service.organizations(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Organizations)
  async deleteOrganizations(
    @graphql.Args() args: DeleteOrganizationsArgs
  ): Promise<Organizations | null> {
    try {
      return await this.service.deleteOrganizations(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
