/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Organizations as PrismaOrganizations } from "@prisma/client";

export class OrganizationsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.OrganizationsCountArgs, "select">
  ): Promise<number> {
    return this.prisma.organizations.count(args);
  }

  async organizationsItems(
    args: Prisma.OrganizationsFindManyArgs
  ): Promise<PrismaOrganizations[]> {
    return this.prisma.organizations.findMany(args);
  }
  async organizations(
    args: Prisma.OrganizationsFindUniqueArgs
  ): Promise<PrismaOrganizations | null> {
    return this.prisma.organizations.findUnique(args);
  }
  async createOrganizations(
    args: Prisma.OrganizationsCreateArgs
  ): Promise<PrismaOrganizations> {
    return this.prisma.organizations.create(args);
  }
  async updateOrganizations(
    args: Prisma.OrganizationsUpdateArgs
  ): Promise<PrismaOrganizations> {
    return this.prisma.organizations.update(args);
  }
  async deleteOrganizations(
    args: Prisma.OrganizationsDeleteArgs
  ): Promise<PrismaOrganizations> {
    return this.prisma.organizations.delete(args);
  }
}
